### ISSUE TITLE
Compatibility with old engines

### ISSUE THREAD

**Issue by malkovDanik** [zerobias/effector#101]
What old version of FF is supported by framework?

**Comment by goodmind** [comment]
last 2 versions of browser

**Comment by malkovDanik** [comment]
Are you planning on supporting later versions? Example, 29 version.

**Comment by goodmind** [comment]
No, use your own babel config

**Comment by malkovDanik** [comment]
I tried, but I get error 'SyntaxError: missing variable name' in FF with use any import function from 'effector'

**Comment by zerobias** [comment]
It is enough to compile `node_modules` with the correctly configured [`preset-env`](https://babeljs.io/docs/en/babel-preset-env)
