### ISSUE TITLE
Usage with NextJS SSR

### ISSUE THREAD

**Issue by flearsmedia** [zerobias/effector#114]
Hi there,

Unfortunately, I am still kinda new when it comes to SSR and I was wondering if you have any examples/extensions/ideas on how to use Effector(-React) with NextJS.

I would appreciate any support.

Thank you!

**Comment by zerobias** [comment]
there are certain projects with effector and ssr

[mlp-ssr **(next.js)**](https://github.com/multiplayground/mlp-ssr)
[hello-nextjs **(next.js)**](https://github.com/bingneef/hello-nextjs)
[realworld riotjs effector universal hot **(riot.js)**](https://github.com/apapacy/realworld-riotjs-effector-universal-hot)

Feel free to look at other projects, builded with effector https://github.com/zerobias/effector/network/dependents

**Comment by Bacher** [comment]
This section will help you:
https://effector.now.sh/docs/api/effector/scope

I've done project with serialization/hydration, works fine.

**Comment by zerobias** [comment]
New russian article [SSR и методики работы с Next.js (часть 1: знакомство с концепцией)](https://www.patreon.com/posts/51754996)
