### ISSUE TITLE
Remove broken link to Unit in sample documentation

### ISSUE THREAD

**Issue by goodmind** [zerobias/effector#140]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%246%20Funded-%2300A156.svg" />](https://issuehunt.io/r/zerobias/effector/issues/140)

Link to `Unit` page in the documentation leads to nowhere and has been added by mistake, we need to remove it

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $6.00)

- [<img src='https://avatars0.githubusercontent.com/u/15912112?v=4' alt='zerobias' width=24 height=24> zerobias](https://issuehunt.io/u/zerobias) ($1.00)
- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($5.00)
### Submitted pull Requests
- [#150 [docs] Remove broken links](https://issuehunt.io/r/zerobias/effector/pull/150)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/zerobias/effector/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by zerobias** [comment]
Also found in [Store](https://github.com/zerobias/effector/blob/master/docs/api/effector/Store.md) docs
