### ISSUE TITLE
Usage with TypeScript is missing

### ISSUE THREAD

**Issue by goodmind** [zerobias/effector#145]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/zerobias/effector/issues/145)

https://effector.now.sh/en/recipes/usage-with-typescript

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)
### Submitted pull Requests
- [#160 #145 Add section usage with Typescript](https://issuehunt.io/r/zerobias/effector/pull/160)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/zerobias/effector/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by Laiff** [comment]
In current project writen on TypeScript we actively use `effector`, I can write this doc section.
