### ISSUE TITLE
restore function doesn't work in REPL

### ISSUE THREAD

**Issue by goodmind** [zerobias/effector#149]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/zerobias/effector/issues/149)

**Code to reproduce the issue:**

```js
const foo = createEvent()
const bar = restore(foo, null)
```

**Expected behavior:**

No errors

**Actual behavior:**

Try Effector crashes

**Versions of packages used:** master

https://effector.now.sh/try/

To reset saved code remove it from localStorage

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#151 #149 Fix crash in try environment while use restore](https://issuehunt.io/r/zerobias/effector/pull/151)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/zerobias/effector/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by zerobias** [comment]
solved in https://github.com/zerobias/effector/pull/151
