### ISSUE TITLE
Compatibility with TV browser (Chrome 47)

### ISSUE THREAD

**Issue by johneisenheim** [zerobias/effector#152]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/zerobias/effector/issues/152)

Hi,
crafting an application with create-react-app, and installing effector/effector-react, in the main file and importing any effector/effector-react functions, the live preview in dev mode returns the following on Chrome 47:

```
Unexpected token {
```

**effector 20.0.0/effector-react 20.0.4**

Thank you

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/zerobias/effector/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by goodmind** [comment]
What target is it? Why so old Chrome?

**Comment by goodmind** [comment]
Doesn't CRA runs node_modules through babel?

**Comment by zerobias** [comment]
Looks like your target isn't supported some new javascript features used by the library. At the moment, the project supports nodejs LTS as the lower bound of supported versions (including browsers with similar language features support), but
it seems reasonable to support older targets as well, we can add it in next version, but I wonder, is it some specific device (TV? Tesla?) or just old Chrome?

**Comment by johneisenheim** [comment]
Hi @zerobias, yes, it is a TV. 
Hi @goodmind yes, CRA runs babel.

Thank you!

**Comment by zerobias** [comment]
Probably issue related with object shorthand properties, used by our terser config, but it's hard to say without proper testing. We asked browserstack.com for help, hope we'll able to publish compatible version soon

**Comment by Laiff** [comment]
Posible problem with argument default value in function call. 

May be we can specify all features used in effector for build correct list of babel plugins to transpile in concrete project?

**Comment by zerobias** [comment]
As far as I know, users unable to configure cra app, so they have to use a library as it is.
I tested on chrome 47 today, looks like we can add compatible build to next release, I just can't decide how to name this file 🤔`import {createStore} from 'effector/legacy'`?

**Comment by Laiff** [comment]
May be `import {createStore} from 'effector/compat'`

**Comment by johneisenheim** [comment]
@Laiff looks good!

**Comment by johneisenheim** [comment]
Hello,
First of all thank you for the fix. We have noticed that also ```effector-react``` has its **compat** version. In this version, it should import ```effector/compat```, not just ```effector```. We have experienced the problem above again, but after we imported effector/compat in node modules everything is ok! Is that correct?

**Comment by zerobias** [comment]
> Hello,
> First of all thank you for the fix. We have noticed that also `effector-react` has its **compat** version. In this version, it should import `effector/compat`, not just `effector`. We have experienced the problem above again, but after we imported effector/compat in node modules everything is ok! Is that correct?

Going to fix this in next release
