### ISSUE TITLE
Usage with React-Native

### ISSUE THREAD

**Issue by tehSLy** [zerobias/effector#153]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/zerobias/effector/issues/153)

Effector is being fully supported by React-Native, which is a good thing to be shown

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)
### Submitted pull Requests
- [#154 Add react-native usage example](https://issuehunt.io/r/zerobias/effector/pull/154)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/zerobias/effector/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by zerobias** [comment]
Example with expo https://snack.expo.io/@zerobias/effector-react-large-list

**Comment by mikaoelitiana** [comment]
What is expected on this ticket? Adding the snack example in the example repository?

**Comment by zerobias** [comment]
> What is expected on this ticket? Adding the snack example in the example repository?

Sure
