### ISSUE TITLE
Effect.prepend -> Effect

### ISSUE THREAD

**Issue by tehSLy** [zerobias/effector#157]
### Current behaviour: 
```js
const effect = createEffect<string, number, Error>();

const prepended = effect.prepend<any>((obj) => JSON.stringify(obj)); //=> Event<any>
effect.fail.watch(handler); //watching other entity, outside of logical scope
prepended({foo: "bar"}); 
```

### Proposed behaviour:
```js
const effect = createEffect<string, number, Error>();

const prepended = effect.prepend<any>((obj) => JSON.stringify(obj)); //=> Effect<any>
prepended .fail.watch(handler); //watching entity in same logical scope, convinient
prepended({foo: "bar"});
```

## Use case
When one needs to prepend effect invocation with specific mapper, result will be 2 entities: event and effect. Then, while prepended effect need to be invoked, one should call event, but `fail`, `done`, `pending` are exists only on source effect.

**Comment by popuguytheparrot** [comment]
Attach was implemented in version 20.13.0. Use it to solve
https://effector.now.sh/docs/api/effector/attach
https://github.com/zerobias/effector/releases/tag/effector%4020.13.0
