### ISSUE TITLE
Missing store.updates in documentation

### ISSUE THREAD

**Issue by popuguytheparrot** [zerobias/effector#163]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/zerobias/effector/issues/163)

Missing store property `updates`

- [x] Add info with examples about store property `updates` to API, 
- [x] Add to Glossary info and types for `updates` property

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#164 #163 Add docs for `Store.updates` event](https://issuehunt.io/r/zerobias/effector/pull/164)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/zerobias/effector/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by zerobias** [comment]
https://github.com/zerobias/effector/pull/164
