### ISSUE TITLE
Bug in reddit example

### ISSUE THREAD

**Issue by Akiyamka** [zerobias/effector#168]
**Code to reproduce the issue:**
https://share.effector.dev/ubCqnRiN

**Expected behavior:**
One request after timeout is enough.

**Actual behavior:**
App fetch data twice after every timeout

**Versions of packages used:**
master branch

**Comment by zerobias** [comment]
Thanks, good catch 👍 
Also additional comments added and improved code readability

**Comment by zerobias** [comment]
https://share.effector.dev/T5CyxSFl
