### ISSUE TITLE
Incomplete forward typings

### ISSUE THREAD

**Issue by abliarsar** [zerobias/effector#174]
Flow example: [link](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgKomGAPAFQHzIDeAUMsgNQDWoAJgFzIDkArhmIwNzEC+xNECADZwoKGKwRhgAexDIY0qAHcRNXHgAU0gA5gAznULkYUaQFsG6TOoA0FMNMtt13AJQM4IAJ58Bw0cgAbiLIemBQTtZhUKAA5ni+QiIowVCh4QDyUAByzBZoztFxyAA+yCB5AEbQCfxJAanleZHYFWbVUAlkxAiyYchQAAwA+qC9ZtpwUpWCKAC88ooqUDQahCbmDNF2DgxtyG7IAPRHoQAW0syCNMjQplB2MILSSrdQ9zt6b-c9fWADIz0cDMEGGYC82ggXwWi2UqjW8lM+W2yF26TSbmIxBOyDMihQRUkyAAtARZnovoSwHZKsx-nAKcBYiA4DMUODIXY9BcrjdqshpJRsacIAAPYHaWZbcLFUno4plNodX4gfpQACMyAWCjhKwRG2R4R2jnRWVyZgOrmOpyeL2+ik+AqFOKUZymqIhBJ512QShQzD0YkUyFiEBA0GACAA-MgVWr1cNQ+GYghhgatbDlmoiiB4vqkdKHqiTdEzXlLWQcbbXncHaivrWoHH-hrE2GI6mHBmdVmsDnYqUmu0amsDYXjYWy2ZDlXnjX3nX9E6sTjyZSZUS5XiAlSPZzzpcfY3hbdxRMpfLc4OldASQR+82BgAmbtLeGERGbU05PIT9EV2c7WPR8oCfNtk0jNMkVfXVsxlK9FSqEcPzHb9zT-aIAJtOd7SLJdBRAsCkw7MFpBg3t+00dYCzQ39i0LLDq1wx1jyAA)
TS example: [link](http://www.typescriptlang.org/play/#code/LAKAlgdgLgpgTgMwIYGMYAICqExQDwAqAfOgN6jrpwxIAmA9hADYCe6A1pLQFzoDkAVxxQ+FKjQbM2AfWm8CoAL6goLAA4YAygIBGAZxRwwaqGEboAvOiQQWAblC0YKJkmroEQlKfMJ6cAHc3WkIiAAp6Ez1uUg84egBbXmxcUIAadCh6ZOFQxQBKXm19Q2MfCEdnV3cANzd0PSg4HNTGowgAcyJKlzcMOrgGpoB5OAA5ASSsXLbIDvQAH3QISZ14bpAnXtr6lamU-D21uA3KUBRGRqoABmlIC4S1JFMdJgwrP0DgsNiEeKm2hksrw9ugCugAPQQhoAC3oAiYtHQ8HicAyCCY9ACyLgqKBehxqPOlygN2keiQCRg0lUGgJVg8-iCcFoPziiV4gMy2SGg3BUNh8MR6DW6Ho7HRmOx4vxYvYoFAAoS-gws286AAtCQ3noCWqoBkdAJSUhdWAOhAkK8MLSYBk9HCEUjReLiRArnAAIyWRlfFlsv4c3lAnltUYTBJg-KQ6EYrGE-yy10gAUBGHPTLqVWO4UBDACPQYT7oDowCDwMAoAD86DdHs90lL5aMKGkgcjHyZwTws064V+-05TRDQ7g4cmUcoArj2JRicyBLncDrpK9jbLFdbWR9n2ZIV78yWR3WP3bo5HvPHCX5salCbRC7lCpT0J1eqaldJWvQyvc+szGj2jmSJLiuVAAEw7l2-oDkGYbjJMF5tJO053qBIBgXA4Hrs2lZtv8UF+vuH6dIsyyrCesEAiMCEJEhTQobe8ZLkm8ogBc7qrthTabjS9CEXuPYkV0p6DpetH0Xy0ZQjO96yuhQA)

**Comment by zerobias** [comment]
this is probably related with [subtyping](https://flow.org/en/docs/lang/subtypes/) not sure what we might do there

@goodmind any ideas?

**Comment by goodmind** [comment]
[flow](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgMIHsBucrDuAVRGDAB4BqAFQD5kBvAKGWXIGtQATALmQHIBXYmF4BuBgF8GoSLEQoM4KHGy58YIiVIBaGvSYt2Ibn0ElREqeGjwkyDWV0QAHpCMBnNFhx5CQ0jQAaT0VlbzV7f1pGZjZOHgEhc0kOCAQAGxwUGEEEMGB0EGQYdCgAdxwOSIAKdAAHMDceaJYYKHQAWx4MFR91P0D9cjB0HgiaCQBKHnwATwYU9MzkFWQ3MChRvzXcEABzannUjKgUFe2AeSgAOX5Ouy310F3kAB9kEFuAI2gDhePTnDvW6bTQfdrfKAHZgMBAFNbIKAABgA+qBYe1anA8p80igALxFErlKAcKp0VodHjbILDHhg5DiCbIAD0zNWAAt0Pw0hxkNA2lAgjA0uhSnyoAKaR5+SUYXCwAiUW44O0IMiwDNahAPATCWUKmSim07tTkLTVusGRMGAxWch2iUUNtgLlkFpaLi3B5nbkgp9+Aq4F7gLsQHAcSgNVqgm5Odzed9kOhWLa2c4VbVcVTHns3bRnbm3mCIXKQPCoABGZAE4r6kmGikm9Y0kYWqCXG7tK0stnC0XiyVmjzJm120rsrFmzVOuM85ClFD8NxZErIXYQEDQF0AfmQpfLFeR683uAQyMb1b1xMqBf2DeN2cFZtbF2ut27PaKIrFMqfDQHsqwmWCqVkeG5bmewyXrW16kLerxAuCPxko2j4to+Ha3Iyn59j+EolFKSYpqmyCet6jyuu69qOm2LoKlGEAxrOvK-iR6YYlmtGFohEJ5lxuz7iBABM0FEgadBGpSbaYe06Ftt2dq4QBUA2kB5ZCWBJ4uuexqiXWN45s8RZfMhEmodJb6yc+j4Kb237KYRI5qcJmkQeq6B6bBt7UChD4WZ2cnbLZSm-oRrFAA)

No idea about TS

**Comment by abliarsar** [comment]
[possible ts solution](http://www.typescriptlang.org/play/#code/LAKAlgdgLgpgTgMwIYGMYAICqExQDwAqAfOgN6jrpwxIAmA9hADYCe6A1pLQFzoDkAVxxQ+FKjQbM2AfWm8CoAL6hQUFgAcMAZQEAjAM4o4YdVDCN0AXnRIILANyhaMFEyTV0CISjMWE9OAB3d1pCegAadAAxOHoAW3QYAA9YCFp9dAJ6IgAKelN9blJPWLjebFw8GPiiSKh6cuEwokUASl4dAyMTXwgnFzcPADd3dH0oOEbK8eMIAHMiftd3DBG4MYmAeTgAOQEyrCaZyDn0AB90CH3deEWQZ2Xh0auDivwXm7g7h8HV0dsWJgpvgAd8Bit0Gt0HEwEkYDxDpUhOwIPRAhA7qAUIxxlQAAzSSDYuLqJBmXRMDDWfxBEI5YoIUq8GZ1BqXfboNroAD03LGAAt6AImLREnBYnBIggmGixRK6hl4BKsTioPjpPokHEYNI1JoMtZPAFgnBaPSSvFmRNWVb1lzeQKhSL0Dd0PR2FKZYE3R70FAMu6VCAHXEAhhjj50ABaEiU-QZCNQSK6ARqpDxsBzCBICkYPUwSL6QXC0WuwMgbEQXFwACMViNtNN5sZlo2kr9bJm2z2CXtfOlsqVAQVPtADsC-LJfo04eLzsCGAE+gwNPQcxgEHgYBQAH50Cqq2ra9J15vjChpC2EtTjSE8Md5ud2XFPoWJidcgymW2bW3uxyuR5fsvTlYc-UVcUAiDB04wTd9IxjaEwzbbc1XzQs51FIc4APasACZ6xpE0zS-Vsu12fZfxmTlWiAzwQOwkdy1wo88JPDctwvK9CNvU173feY31mU4Lg+W5m2-cieyoiYaLogdvUY8DRxAUAiLpUgr14AFMF-GE4VoNo1N4kitOhWF4V-HSaOMxtTO-fTLI7W0bJAIA)

**Comment by zerobias** [comment]
we can allow flow to assert type relations explicitly [repl](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgKomGAPAFQHzIDeAUMsgNQDWoAJgFzIDkArhmIwNzEC+xxNEBABs4UFDFYIwwAPYhkMGVADuomlgCCeABQyADmADODEmXIwoMgLYN0mTXgA0pCmBm22DngEoGcEACe-IIiYgqS0nIKSqpQ6jgyjsgAYpY2yAk6+kYmLuZpHvap1k55boXYmT5+gcHCoigAbqLIhmBQFVhtUKAA5nh1oU0t3QDyUAByzOl22N19yAA+yCDTAEbQAwL1Yc1QK9Odq1YbUANkxAhybchQAAwA+qBXVnpw0mtCKAC80Spq2kIFmsDG6SXKBysyG43mQAHo4a0ABYyZhCGjIaCWKBJGBCGTKTFQbHgwxE7GXa5gW6PQxwKwQB5gAJ6CBk35-WI0QEKAqtdrg9z8-YwvgI5BWJQoeZSZAAWgIX0MZJlYCSa2Y1LgyuAvRAcE+KGZrKShhRaIxG2QMkoxHFEAAHvS9F9Qe0FgrhQtlsdTpSQDcoABGZC-RT-OI84HpMHICFjSbTaGw8V4gnkpSk622u2I5RI95xlnS83o5DKFDMQziJTIXoQEDQYAIAD8yH9gaDD3rjZ6CAe0dDnLUXXdIH6Ub5sfj7XGUyhMLIqfxhKxmbjZLXUA71OD3YbTf7biH4a5o5646WkNOprHE6BU4FcaFCfni+X6a3WZtYsRSpV7qyp6kphKqRYmsiqJlluuaYk6ryul6l4+us0DygQ8zjjutwAEwnjEAKELyILCnO0yCm6IopoiaarsSSh8FcAa7jh+69s2A5pPhEbqJhvRXr6myTiRr7kc+lHJvCNErhmOIbtm2FQKxPaHkyMjcWefE6A+ImzomVgUcKkkIrRslZjBQA)

Note that `forward({ from: str, to: strOrNum })` now works without explicit generics

**Comment by zerobias** [comment]
@abliarsar looks like we suggest similar solutions 🙃

**Comment by zerobias** [comment]
Looks like my solution for flow don't work in practice

`Could not decide which case to select bla bla bla`
Perfect, flow prevent us from improve type inference again

**Comment by zerobias** [comment]
@goodmind solution for flow works as expected

**Comment by zerobias** [comment]
Not sure if I realize what changed in typescript errors
https://github.com/zerobias/effector/commit/8f587a8ac31c8ea8ed87e6dd8532b9a2028c7340#diff-c89e1c48f65366897054a19c423ee51cL1411
Did I miss something?

**Comment by abliarsar** [comment]
I think, we cannot use only one generic argument in typescript, [that](http://www.typescriptlang.org/play/#code/LAKAlgdgLgpgTgMwIYGMYAICqExQDwAqAfOgN6jrpwxIAmA9hADYCe6A1pLQFzoDkAVxxQ+FKjQbM2AfWm8CoAL6hQUFgAcMAZQEAjAM4o4YdVDCN0AXnRIILANygA9E-RCU9ALaeY0dBBgADyh0JkgMKHp0fRgMSA84ahQQ3RgACyQAN3MBOGdXWhgUJiRqdAR3MwsEejgAd1LaQiIACnpTfV5SBDgvXmxcZvt0SP7hZsUASl4dAyMTKohQQuLSjAqIZPMIctqGuCaCegAadAAxXs90INgIWn10I9b2qE7ScsuxwYuvIlPRrDjJ5TGZ6QzGUzbZZFEplTKlaJQOBffD6JGQADmRGhqzhCLRcAA8nAAHICTwovAEzHoAA+-nJqTg2JAK1hGHhcAZFMBgwgjPgLLZa3QnJsdkwlNsLCFMJFYs8YECMB4vPwQnYEHodQgLNAHggaKoAAZpPEvOokGZdEwMNYavVGi13j0+oi4P96Lx+VcpugXNE0vQBExaOUkGAmPrGEa4Kb9EgfNI1JoHtZdo6Ds6Pm6CZ7eAT0H6A-ogyGw6l0PR2CoQAHPLUMNTkugALQkW36B7NqCnXQCEJILtgDEQJA2iIaGCnUvB0PoSvV6OGkJwACMVgz+1o2ddPLzIy97uJZN9k0oy9ja+kGN88DAKE3Du3VPREAxdO5TJnb6xu8+7r5sepLkkW561gGnbduiLbtugDZlD2IxTjOZbzsgkaXquABMT57E6LoAQSJ7kkBhbFq4-YYreYZgAg6B1BgdBhrYVaZPATD0HQWFUNhN53sYj72vhByvsY74-uJH70j6TKtIRuZIiRnhkUiYEQa4s7lguGBLiAz4EXuvDSpgQGKsqtBTKABlZt0AHmSqQEmep+kiTudluiZqlclZID5IGc5hhhUauZm7lGfBSqOYeBZqRRC4CNRKroHRDFMbQLE7PQ7FwJx3F+XWrgoLYWohAIMRVlIlUYLeASCTYcAYuSvghFqdToNwLTWW5Yk0jJArMs6EXESBKkxe6fr+q4SBMPoURUTRKX0YxNgZeKbEcVxtBAA) is the reason why.
Signature with one type works incorrectly with unknown type

**Comment by abliarsar** [comment]
Fixed in #229
