### ISSUE TITLE
Change `sample` name to be similar to `combine`

### ISSUE THREAD

**Issue by goodmind** [zerobias/effector#179]
**Code to reproduce the issue:**

```js
const foo = createEvent()
const bar = createEvent();
const sampled = sample(foo, bar);

console.log(sampled.shortName);
```

**Expected behavior:**

```
sample(foo, bar)
```

**Actual behavior:**

```
foo
```

**Versions of packages used:** master

**Comment by zerobias** [comment]
Complex dynamic name calculations are out of scope as both `combine` and `sample` support name definition via babel-plugin
