### ISSUE TITLE
`createComponent` not supporting hooks yet

### ISSUE THREAD

**Issue by tehSLy** [zerobias/effector#183]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/zerobias/effector/issues/183)

**Code to reproduce the issue:**
```
const $store = createStore();
const App = createComponent($store, (props, state) => {
  const [count, setCount] = useState(0)

  return <div>{state} {count}</div>
});
render(<App />, document.getElementById("root"));
```

**Expected behavior:**
No errors

**Actual behavior:**
`Error: Invalid hook call. Hooks can only be called inside of the body of a function component. `

**Versions of packages used:**
Latest (effector: 20.1.2, effector-react: 20.2.2)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)
### Submitted pull Requests
- [#188 createComponent hooks](https://issuehunt.io/r/zerobias/effector/pull/188)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/zerobias/effector/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by zerobias** [comment]
looks like this going to be pretty hard task, because of differences between components and hooks nuances
but yes, you’re right, it’s important to have consistent api and we need to do that

**Comment by zerobias** [comment]
Note that piling wrappers up is not an option

![hadouken](https://user-images.githubusercontent.com/15912112/63462258-2c90bc00-c463-11e9-8377-47f404c60f44.png)

**Comment by zerobias** [comment]
Fixed in https://github.com/zerobias/effector/pull/188
Will be published in next effector-react release
