### ISSUE TITLE
domain api. Rename event, store, effect to createEvent, createStore, createEffect

### ISSUE THREAD

**Issue by belozer** [zerobias/effector#186]
event.
Base api for create event - `createEvent`, but in domain `domain.event`....
but hook named as `domain.onCreateEvent`....

store.
Base api for create store - `createStore`, but in domain `domain.store`....
but hook named as `domain.onCreateStore`....

effect.
Base api for create store - `createEffect`, but in domain `domain.effect`....
but hook named as `domain.onCreateEffect`....

## Proposal
Rename `domain.event` to `domain.createEvent`
Rename `domain.store` to `domain.createStore`
Rename `domain.effect` to `domain.createEffect`
Mark `domain.event` and `domain.store`, `domain.effect` as **deprecated**

OR
Rename base api `createEvent` -> `event`, `createStore` -> `store`, `createEffect` -> `effect`
and mark `createEvent`, `createStore`, `createEffect` as **deprecated**

**Comment by zerobias** [comment]
I'm agree with renaming `domain.*` to `domain.create*` 👍 

Replacing `createEvent` with `event` is not convenient, as `event` is common name for events itself



New aliases can be added [here](https://github.com/zerobias/effector/blob/master/src/effector/domain/domainFabric.js#L97)

**Comment by zerobias** [comment]
Implemented in [effector 20.7.0](https://github.com/zerobias/effector/releases/tag/effector%4020.7.0)
