### ISSUE TITLE
Support for flutter and persistence? 

### ISSUE THREAD

**Issue by feat7** [zerobias/effector#208]
Do we have any plans to make effector available for flutter? 

Also, I am looking for a persistence manager for example I use mobx-persist while using mobx.

Any update will be appreciated.

**Comment by zerobias** [comment]
We have certain libraries for working with localStorage
https://github.com/lessmess-dev/effector-localstorage
https://github.com/MrFranke/effector-persist

Also, this can be implemented via effects, one for persisting and one for retrieving: https://share.effector.dev/1oOz6104

```js
import {createStore, createEffect} from 'effector'

const save = createEffect({
  handler(data) {
    localStorage.setItem(
      'user',
      JSON.stringify(data, null, 2)
    )
  }
})
const load = createEffect({
  handler() {
    return JSON.parse(
      localStorage.getItem('user')
    )
  }
})

const user = createStore({name: 'jack'})
  .on(load, (_, {result}) => result)

// save each new store state
user.watch(save)

load()
```

**Comment by zerobias** [comment]
As for flutter, it possible, effector itself used only common js (without Proxy, decorators and other odd stuff), just need some wrapper being written in dart. We already did it for [reasonml](https://github.com/zerobias/effector/tree/master/src/reason), and we will appreciate any help with dart

**Comment by Bannerets** [comment]
Dart in Flutter, unlike React Native, compiles to the machine code (in the debug mode it gets interpreted inside Dart VM), thus it's not comparable to ReasonML w/ BuckleScript.
Though, you can still run JS code in WebView, but that's far from ideal.
There's also new and very experimental "[web support for Flutter](https://flutter.dev/web)" that has low performance for now. Effector can be ported there, then Dart bindings are needed. You can use it in a web browser or as a PWA.

**Comment by zerobias** [comment]
@Bannerets we aren't locked to js implementation of the library
Effector's [kernel](https://github.com/zerobias/effector/tree/master/src/effector/kernel) is platform-independent, as it uses only well-known data structures: stacks and heaps, so we might port it to Dart

**Comment by Bannerets** [comment]
Yeah, also mobx already did that: https://github.com/mobxjs/mobx.dart

**Comment by zerobias** [comment]
Porting effector to another languages is out of scope
