### ISSUE TITLE
Add Vue bindings

### ISSUE THREAD

**Issue by Kelin2025** [zerobias/effector#22]
I can help with Vue bindings 'cause I want to try it on my side-projects (:

**Comment by zerobias** [comment]
Can you provide some examples of using them together? I'm not familiar with vue yet, so I definitely need a help here 🤕

**Comment by Kelin2025** [comment]
A little FYI 
- Vue has mixins (and global mixins) that will be merged into vue components (vue component is a plain object). Hooks are concatenated
- Vue has component hooks - might be useful: `beforeCreate` to modify component options, `created` to work with initialized component
- You can trigger `$forceUpdate` for components bypassing reactivity
- You can also create a bicycle - create Vue component, pass store state to data and update it reactively inside subscription. Then pass this component to computed properties. This way doesn't require `$forceUpdate`. Vuelidate works [like this](https://github.com/monterail/vuelidate/blob/master/src/index.js#L544-L594)

I can write some examples tomorrow or so, now I'm going to bed 😴
