### ISSUE TITLE
Usage with v-model? (Vue)

### ISSUE THREAD

**Issue by maximelebreton** [zerobias/effector#237]
Hello,
is there a way to bind a `store` on `v-model` (read/write)?

```vue
<input v-model="search">
```

```js
const $search= createStore('hey')
const search= ???
```
Thanks!

**Comment by maximelebreton** [comment]
I tried to mimic the [Vuex solution](https://vuex.vuejs.org/guide/forms.html#two-way-computed-property), but it doesn't work:


_note: In this example im using the [Vue composition API](https://vue-composition-api-rfc.netlify.com/) plugin_

**search.js**
```js
const $search = createStore('hey');
const searchInputChanged = createEvent('input changed');
$search.on(searchInputChanged, (state, payload) => payload);

export {
  $search,
  searchInputChanged
}

```
**search.vue**
```vue
<template>
  <input v-model="state.search">
</template>

<script>
import { computed,  reactive,  watch,  createComponent } from "@vue/composition-api";
import { $search, searchInputChanged } from "./search";

export default createComponent({

  setup(props, context) {
    const state = reactive({
      search: computed({
        get() {
          return $search.getState();
        },
        set(value: string) {
          searchInputChanged(value);
        }
      })
    });

    watch(
      () => state.search,
      (value, prevValue) => {
        console.log(value); // nothing happens...
      }
    );

    export {
      state
    }

  }
})
</script>
```

**Comment by zerobias** [comment]
I would suggest using store.watch directly. Yes, store has its own method `.watch` and it much more straightforward: state changed → `.watch` called, without any proxies nor implicit observables

```js
export default createComponent({
  setup(props, context) {
    const state = reactive({
      search: computed({
        get: $search.getState,
        set: searchInputChanged
      })
    });
 
    $search.watch(state => {
      console.log("$search", state);
    });

    return {
      state
    };
  }
});
```

You can try this example on codesandbox https://codesandbox.io/s/effector-with-vue-kr2v7

**Comment by maximelebreton** [comment]
Thanks @zerobias, and really like your shorthand for computed get/set (8 lines to 4)!

But **I still have a bug in my case**, in combination with **events**, so I reproduce the case on a fork of your codesandbox (I added `effector-vue` and few lines of code):
https://codesandbox.io/s/effector-with-vue-4hygh

When you write something in the input, and trigger an event (debounced or not), the input **came back to his default state**...

Am I miss something, or is it a bug?

I put a @debugger breakpoint to understand what's going on, and this behaviour seems to come from a`flushCallbacks` function, if this can help...

Thanks a lot for your help.

**Comment by zerobias** [comment]
Seems like `computed` works not as expected, as everything is ok without it:

```js
  setup(props, context) {
    const state = reactive({
      get search() {
        return $search.getState()
      },
      set search(value) {
        searchInputChanged(value)
      }
    })

    const debounceInput = debounce(() => {
      searchTriggered()
    }, 500)

    $search.watch(state => {
      debounceInput()
    })

    return {state}
  }
```

Interestingly, everything works even without `reactive` at all

```js
export default createComponent({
  effector: {
    $text
  },
  setup(props, context) {
    const state = reactive({
      get search() {
        return $search.getState()
      },
      set search(value) {
        searchInputChanged(value)
      }
    })

    const debounceInput = debounce(() => {
      searchTriggered()
    }, 500)

    $search.watch(state => {
      debounceInput()
    })

    return {state}
  }
})
```

**Comment by zerobias** [comment]
Looks like a bug in `computed` implementation. Even without effector, any state change inside `set` method leads to odd behavior

https://codesandbox.io/s/effector-with-vue-268n6

```js
export default createComponent({
  setup(props, context) {
    const search = ref("ok");
    let input = "hey";
    return {
      state: reactive({
        searchRef: search,
        search: computed({
          get: () => input,
          set(value) {
            input = value;
            // this assignment ruin everything
            search.value = value;
          }
        })
      })
    };
  }
})
```

**Comment by maximelebreton** [comment]
> Interestingly, everything works even without reactive at all

You mean this?

```js
// ...
    const state = {
      get search() {
        return $search.getState()
      },
      set search(value) {
        searchInputChanged(value)
      }
    }
// ...
```
Yes, it's working!

Don't know if there is some drawbacks, but I like this one!

Thanks for the help, i've posted an issue on the vue composition repo.

**Comment by maximelebreton** [comment]
Hello @zerobias,
as mentionned in this discussion https://github.com/vuejs/composition-api/issues/174#issuecomment-552476052
, it's seems to be related to **effector**, who's not share the Vue's reactivity system.

I thought that `$myValue.getState()` was understood by **Vue**'s reactivity system, and **vue-effector**' was just a helper to inject the `$myValue.getState()` as `$myValue` in **Vue** templates, but now I assume that there is some other magic under the hood?

If **effector** not share the Vue's reactivity system, the documentation should be more clear on limitations, because it currently suggests that **effector** reactivity system is 100% compatible with **Vue**, wich is apparently not.

Thanks for your clarifications

**Comment by zerobias** [comment]
At first Vue should provide a way to interact with another libraries.

We have at least two ways to share reactivity:`symbol-observable`, which used by `redux`, `rxjs` `most` and many others ([example](https://effector.now.sh/en/api/effector/fromObservable)), and even more popular `.subscribe` interface to interact with a rest of ecosystem.

And instead of using such ways to communicate and collaborate, Vue rejecting any possibility to interact with exterior reactivity systems, blaming them to not to obey. We have a much better reactivity system. I'm think this is not fair.

**Comment by maximelebreton** [comment]
Ok, I understand this is not fair BUT you can't cheat with your users like this.

I came to **Effector** because I read on the main repo that you can use it with **Vue**, and this is the only reason that pushed me to try it.

> ![image](https://user-images.githubusercontent.com/1072425/69446844-8f8d3a00-0d55-11ea-928d-1abd698dbcd3.png)

But if it's not 100% compatible with Vue, I will drop it, even if I agree this is unfair.

**Vue** solve too many things to depends on a state managment library who is not 100% compatible with it.

I am very disappointed to not have been warned by **Effector**'s documentation about these **limitations**.
I hope you'll fix this very soon on documentation, because this is a huge drawback, and you will lose the trust of your users if you're not honest about this.

I'm so sorry because I was really in love with Effector, and I hope there will be a solution.
Is there any discussions with the Vue team about this (a way to interact with another libraries)?

Thanks

**Comment by zerobias** [comment]
> Ok, I understand this is unfair BUT I think you can't promote **Effector** as a state manager for **Vue**, because it's not fully compatible, and it will misleads many **Vue** users.

We supporting current public api, composition api is still in development, as it has version _0.3.2_. Please consider using current public api of that framework, not future experimental library, as we cannot depend on experimental features anyway

**Comment by zerobias** [comment]
[`effector-vue` documentation page](https://effector.now.sh/en/api/effector-vue/effector-vue)
