### ISSUE TITLE
[REPL]: restore with store argument crashes REPL

### ISSUE THREAD

**Issue by Tauka** [zerobias/effector#243]
**What is the current behavior:**
REPL crashes with following code:
```javascript
const $store = createStore(null);
const $newStore = restore($store, null);
```

**What is the expected behavior:**
Not crashing

**Which versions of Effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of Effector?:**
REPL

**Comment by zerobias** [comment]
Thanks for report! Will fix this soon
