### ISSUE TITLE
Effector website theme is not properly set

### ISSUE THREAD

**Issue by Tauka** [zerobias/effector#283]
**What is the current behavior:**
When I change theme to non-system mode (i.e. i have "Dark" in my system, but I toggled it to "Light"), and reopen website, it flashes from "Light" to "Dark", but when I click on other pages it goes "Light" again

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://effector.now.sh/try, https://codesandbox.io or similar**
* Open website on macOS
* Change theme to non-system (e.g. if you have set "Dark" in your system, set it to "Light") in theme website
* Reopen website and go to other pages

**What is the expected behavior:**
When I toggle it to be "Light", it should stay "Light" without any temporary changes "Dark"

**Which versions of Effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of Effector?:**
macOS 10.14.4
latest version of website

**Comment by zerobias** [comment]
We've had to add an odd hack for dynamic system theme changes because docusaurus doesn't manage it properly.

I found a way to detect and save manual theme changes, it should help. Feel free to open new issue or mention me here if it doesn't.
