### ISSUE TITLE
last example in https://effector.now.sh/docs/api/effector/restore not working

### ISSUE THREAD

**Issue by WoodenPC** [zerobias/effector#287]
**What is the current behavior:**

Hi. It seems that `restore` function not working correctly and throws an exception. I am looking at last example at https://effector.now.sh/docs/api/effector/restore.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://effector.now.sh/try, https://codesandbox.io or similar**

Just ctrl+C and ctrl+V code in docs/api/effector/restore
https://share.effector.dev/Nig3OReU

**What is the expected behavior:**
Result of restore probably should have `watch` function.
**Which versions of Effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of Effector?:**
`"effector": "^20.9.1",`

**Comment by zerobias** [comment]
Documentation was incorrect, the last overload of that method returns object with stores rather than another store

```js
import {restore} from 'effector'

const {foo, bar} = restore({
  foo: 'foo',
  bar: 0,
})
foo.watch(foo => {
  console.log('foo', foo)
})
// => foo 'foo'
bar.watch(bar => {
  console.log('bar', bar)
})
// => bar 0
```

[Try it](https://share.effector.dev/NQX0kotI)

Thanks for help!
