### ISSUE TITLE
dependencies and devDependencies

### ISSUE THREAD

**Issue by thoughtbyte** [zerobias/effector#297]
Why are things like redux, vue, all of the babel packages and types, various testing tools, etc. listed in the dependencies and not the devDependencies? It makes it a bit more difficult to get a sense of what the package depends on from a user perspective.

**Comment by zerobias** [comment]
This is a development-only package, you can see the real `effector` package.json [here](https://github.com/zerobias/effector/blob/master/packages/effector/package.json). The key is that none of development-only dependencies is not mentioned in public package.json at all. Anyway, it's much better to [observe dependencies in npm directly](https://www.npmjs.com/package/effector?activeTab=dependencies).

However, we'll update development package according to your request.
