### ISSUE TITLE
Cross-domain Connections?

### ISSUE THREAD

**Issue by mikecann** [zerobias/effector#298]
Hi,

Just getting started with Effector, really like it so far.

So I have sepparated my state, events and effects into domains but there are situations where one domain needs to communicate with another and I am wondering what the correct approach should be.

So for example say I have an auth domain with a login effect:

```typescript
// file: domains/auth.ts

/**
 * Types
 */

export type State = {
  token: AuthToken | undefined;
};

/**
 * Domain
 */

export const domain = createDomain(`auth`);

/**
 * Events
 */

export const events = {
  setToken: domain.createEvent<AuthToken | undefined>(`auth token set`),
};

/**
 * Effects
 */

export const effects = {
  login: createApiEffect(domain, "auth.login"), // takes in '{  username: string, password: string }' and returns '{ token: string, user: Me }'
};

/**
 * Store
 */

const initialState: State = {
  token: undefined,
};

export const store = domain
  .store<State>(initialState)

  .on(events.setToken, (state, token) => update(state, { token }))

  .on(effects.login.done, (state, { result: { token } }) => update(state, { token }))
```

So this is a nice standalone domain that you can login with and updates the local store with the token once logged in.

Then we have the "me" domain:

```typescript
// file: domains/me.ts

/**
 * Types
 */

export type State = Me | undefined;

/**
 * Domain
 */

export const domain = createDomain(`me`);

/**
 * Events
 */

export const events = {
  set: domain.createEvent<State>(`set me`),
};

/**
 * Effects
 */

export const effects = {
  load: createApiEffect(domain, "me.get"),
 // ... and other things related to "me"
};

/**
 * Store
 */

const initialState: State = undefined;

export const store = domain
  .store<State>(initialState)

  .on(events.set, (state, me) => me)

  .on(effects.load.done, (state, { result }) => result);
```

Now this too is a nice standalone domain. 

The issue is now that the auth login effect returns both the `token` and `me` from the api call. So I have a cross-cutting concern here.

The question is how do I take the `me` from the login call in the auth domain and set it on the store in the me domain.

My thinking so far has been to add another file to "connect" the two domains:

```typescript
// file: domains/index.ts

import * as Me from "./me";
import * as Auth from "./auth";

export const connectDomains = () => {  
  Auth.effects.login.done.watch(({ result: { user, token } }) => {
    Me.events.set(user);
  });
};

export { Auth, Me };
```

Thoughts?

**Comment by zerobias** [comment]
You can transform events with [event.map](https://effector.now.sh/docs/api/effector/event#mapfn) and connect them directly with [forward](https://effector.now.sh/docs/api/effector/forward).

```js
import {createEffect, createEvent} from 'effector'

const login = createEffect()
const setMe = createEvent()

forward({
  from: login.done.map(({result}) => result.user),
  to: setMe,
})
```

[Try it](https://share.effector.dev/QmL7H0KT)

**Comment by mikecann** [comment]
Awesome, havent used forward yet, looks like it should simplify things.

So just to confirm, you would take this "cross-domain" logic and put it in a module higher up in your program?

**Comment by zerobias** [comment]
Yeah, sure
