### ISSUE TITLE
Undo / Redo

### ISSUE THREAD

**Issue by mikecann** [zerobias/effector#315]
Redux docs provide an excellent example of how to go about implementing Undo / Redo: https://redux.js.org/recipes/implementing-undo-history

Im wondering how one would go about implementing Undo / Redo in Effector given that there could be multiple stores?

Edit: perhaps something like this? https://svelte.dev/repl/e8f557a785da42d686722620cd2750b8?version=3.12.1

**Comment by mikecann** [comment]
![image](https://user-images.githubusercontent.com/215033/76682508-a541aa80-6637-11ea-923d-10f6d4336741.png)

I think the key difficulty lies in the fact we want to be able to update a lower part of the state tree but have undo redo still work on the whole tree..

I believe Mobx State Tree solves this problem but I want to avoid that because of all the magic.

**Comment by zerobias** [comment]
There no such thing as "state tree", you can add undo/redo for any particular store

https://share.effector.dev/N3It1fU7

**Comment by mikecann** [comment]
@zerobias thank you very much for that example, that really helps out :)

I think my second point (about the state trees) is a sepparate question, I should have asked it in a seapparate issue.. but it is kind of related..

But basically, the question is, what if you have a computed store which is combined from two counter stores. This computed store is your "app state"..

You want the undo / redo functionality to operate at an app level thus you want it to operate on the computed store? So how do you do undo / redo but still have the counter stores update their current state once the computed store history change?

I think its a circular reference / circular state issue.. Thoughts?

**Comment by zerobias** [comment]
When we have common history for several stores, that imply history object which looks like this:

```json
{
  "timeline": [{"foo": -1, "bar": -10}, {"foo": -10, "bar": 10}],
  "position": 1
}
```

So we can add support for several stores by adjusting `.on` handlers inside `createUndoRedoAPI`:

```js
// before
store
  .on(validUndo, (_, {timeline, position}) => timeline[position - 1])
  .on(validRedo, (_, {timeline, position}) => timeline[position + 1])


// after
for (const key in stores) {
  stores[key]
    .on(validUndo, (_, {timeline, position}) => timeline[position - 1][key])
    .on(validRedo, (_, {timeline, position}) => timeline[position + 1][key])
}
```

Thereby removing restrictions from application shape: `createUndoRedoAPI` just not interested in how we combine stores in application

https://share.effector.dev/gyXeuXlb

![image](https://user-images.githubusercontent.com/15912112/76716674-3309bc80-6742-11ea-9bee-d53e745a2007.png)

**Comment by mikecann** [comment]
Brilliant! Thanks for that :)
