### ISSUE TITLE
Store evaluation order

### ISSUE THREAD

**Issue by dhmk083** [zerobias/effector#326]
```js
const ev = createEvent()
const reset = ev.filterMap(x => { if (x === 2) return x })

const a = createStore('a').on(ev, x => x + x)
const b = createStore(1).on(ev, x => x + 1)

const c = combine(a, b, (a, b) => [a, b])
  .on(reset, () => 'override')
  
c.watch(x => console.log('c: ', x))

ev(2)
// ['a', 1]
// 'override'
// ['aa', 2]

console.log('state', c.getState())
// ['aa', 2]
```

I expected to see `c.getState() === 'override'`, but it's not true. Shouldn't `.on()` handler on a derived store take precedence over combining function?

**Comment by zerobias** [comment]
No, `combine` is executed after all plain computations like `.on`. [Computation priority](https://effector.now.sh/docs/advanced-guide/Computation%20priority) in docs.
In general, if you need to know explicit order of computations, something is going wrong.

Both `.on` and `.reset` on computed stores are not recommended and should be treated as an escape hatch, not as a normal workflow: these methods broke semantic of computed, derived value by forcing it to acts on its own and expectations mismatch in such cases are quite common.

**Comment by dhmk083** [comment]
Ok, so I have this case: two stores `a` and `b` and an event (or many events). The resulting store `c` depends on `a` and `b`, but whenever the event is fired, `c` must be set to another value and keep it until the next `a` or `b` update. 
I've made another example with a helper intermediate store, but I think it's too complicated.
```js
const ev = createEvent()
const reset = ev.filterMap(x => { if (x === 2) return x })

const a = createStore('a').on(ev, x => x + x)
const b = createStore(1).on(ev, x => x + 1)

const helperInitial = {}
const helper = createStore(helperInitial).on(reset, () => ({}))
const calcC = () => {
  let prev = helperInitial
  return (a, b, helper) => {
    if (prev !== helper) {
      prev = helper
      return 'override'
    }
    return [a, b]
  }
}

const c = combine(a, b, helper, calcC())
  
c.watch(x => console.log('c: ', x))

ev(2)
// ['a', 1]
// 'override'

console.log('state', c.getState())
// 'override'
```

Is that a preferred approach?

**Comment by zerobias** [comment]
Here we have two separate cases: in first, `c` should _update_, in second - _reset_. For splitting separate cases effector has method [split](https://effector.now.sh/docs/api/effector/split). And for reading values of stores in some case effector has method [sample](https://effector.now.sh/docs/api/effector/sample#samplesource-clock-fn-greedy-target).


```js
import {createEvent, createStore, split, sample} from 'effector'

const ev = createEvent()

const a = createStore('a').on(ev, x => x + x)
const b = createStore(1).on(ev, x => x + 1)

const {update, reset} = split(ev, {
  update: x => x !== 2,
  reset: x => x === 2,
})

const c = createStore(['a', 1])
  .on(reset, () => 'override')

sample({
  source: [a, b],
  clock: update,
  target: c,
})

c.watch(console.log)

ev(2)

```

It's reading as "during `ev` call, when payload is equal 2, send to `c` value `'override'`, otherwise read current values of `a` and `b` and send them to `c` as array"

[Try it in repl](https://share.effector.dev/BwjhQld0)

**Comment by dhmk083** [comment]
Thanks for the explanation.
