### ISSUE TITLE
Cycle protection

### ISSUE THREAD

**Issue by PFight** [zerobias/effector#331]
How about adding some cycle protection? Now effector with cycle blocks browser until max callstack exceeded: https://share.effector.dev/s1OCDGzu

For example, restrict max count of node calculation per tick. Smth like this:
```
graphite.frameCalculations++;
if (graphite.frameCalculations > MAX_FRAME_CALCULATIONS) {
    throw new Error("Max node calculations per frame exceeded. Probably, you have cyclic depenency. Please, investigate error callstack to find it.");
}
if (!graphite.resetTImeout) {
   graphite.resetTImeout = setTimeout(() => {
         graphite.frameCalculations = 0;
         clearTimeout(graphite.resetTImeout);
    });
}
```

**Comment by zerobias** [comment]
Repl indeed has cycle protection, in case when your code stuck in infinite loop, after reloading page it will insert an error to beginning of the code

![ezgif-3-787c52b88678](https://user-images.githubusercontent.com/15912112/80918465-cee09d80-8d6d-11ea-970c-7d7a637698af.gif)


The main issue in your example is synchronous console rendering, which consumes a lot of resources, without console.info this example executed in milliseconds

https://share.effector.dev/9ZXy7FDz
