### ISSUE TITLE
blog design is broken

### ISSUE THREAD

**Issue by thecotne** [zerobias/effector#332]
<img width="1324" alt="Screen Shot 2020-05-06 at 01 40 42" src="https://user-images.githubusercontent.com/1606993/81118851-ae197300-8f3a-11ea-9129-ab3d6144bdee.png">

**Comment by zerobias** [comment]
Thanks for report! Seems like an issue with docusaurus styles

**Comment by thecotne** [comment]
this broke it 8b863ce40a3b180e9c3c9342cdd9b5be1b30fdeb @kobzarvs
