### ISSUE TITLE
Remove event.filter(fn)

### ISSUE THREAD

**Issue by sergeysova** [zerobias/effector#333]
It was deprecated. Use `.filterMap(fn)` and `.filter({fn})`

**Comment by igorkamyshev** [comment]
Hello! I am just curious. Why `.filter(fn)` was changed to `.filter({fn})`? 🤓

**Comment by sergeysova** [comment]
Because `.filter(fn)` duplicates `.filterMap(fn)`.

But `.filter({ fn })` work as expected.
