### ISSUE TITLE
Big lists

### ISSUE THREAD

**Issue by PFight** [zerobias/effector#337]
Hello, I have table with great ammount of rows (up to 100k+). Data is loading dynamicly, and each row has it's state (expanded/collapsed and etc.). I have found next example https://effector.now.sh/docs/api/effector-react/useList how use effector with lists. But there you are recreating whole list on every change. It's looks as a not good solution, when you have 100k rows - recreate array when you need only expand or highlight single row.

What can you suggest as best practice for this case? May be create store, with object like: `{ rows: [] }`, so there will no need to recreate array, just copy same array to new instance in reducer.

**Comment by zerobias** [comment]
100k, wow. Consider using some sort of virtualization, as 100k items greatly exceed the capabilities of the web platform: even pure react implementation is [unacceptably slow](https://share.effector.dev/B44g3LR1)

Here is [an article about virtualization](https://blog.logrocket.com/rendering-large-lists-with-react-virtualized-82741907a6b3/) in react

**Comment by PFight** [comment]
Yes, we use virtualization, but it affects only view layer. Model can contain some part of this 100k rows, that already loaded, and ammount of rows can be quite big. So, question is how to represent data layer in this case.

**Comment by zerobias** [comment]
In that case you can use `{rows: []}` as you suggested above. That's a common pattern for handling mutable data in effector. For example, [dynamic form fields, saving and loading from localStorage with effects and mutable `{ref: Map}`](https://share.effector.dev/1oOz6104)
