### ISSUE TITLE
event.prepend(...) doesn't work with undefined

### ISSUE THREAD

**Issue by goodmind** [zerobias/effector#35]
**Code to reproduce the issue:**

```js
import { createEvent } from 'effector'

const click = createEvent()
click.watch(console.log)

const preclick = click.prepend(n => n)

preclick()
```

**Expected behavior:**

`undefined` in console

**Actual behavior:**

`click.watch` doesn't get called

**Versions of packages used:**

0.18.1

**Comment by zerobias** [comment]
fixed in ba29b8b20a4c3d026f6fc4e1454da050eaa36fd6
