### ISSUE TITLE
store.subscribe should accept observer object

### ISSUE THREAD

**Issue by yogurt1** [zerobias/effector#357]
**What is the current behavior:**

createEffect().subscribe throws *watch requires function handler* when observer object passed

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://effector.now.sh/try, https://codesandbox.io or similar**

https://stackblitz.com/edit/rxjs-wryuan
Example with RxJS

**What is the expected behavior:**

createEvent() and createStore() works as expected
createEffect() should work too

**Which versions of Effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of Effector?:**

20.16.1
effector@20.16.1/effector.cjs.js

**Comment by yogurt1** [comment]
https://stackblitz.com/edit/rxjs-eglbkr?file=index.ts

Here you can see that `Symbol.observable` works as excepted

**Comment by zerobias** [comment]
Can't reproduce, your example is working, and even more, it's working in such many ways at the same time so it's hard to understand what your point exactly is.

Effect is literally [an event](https://github.com/zerobias/effector/blob/master/src/effector/createEffect.js#L22), they cannot differ in behavior. Moreover, they are indeed working with Observers, did you mean store.subscribe?

**Comment by zerobias** [comment]
I found that stores indeed has no support for Observers in .subscribe and there is no reason for such disadvantage

**Comment by zerobias** [comment]
Fixed in `effector 20.16.2`
