### ISSUE TITLE
Describe motivation for creating or using this library

### ISSUE THREAD

**Issue by sesm** [zerobias/effector#37]
Currently `README.md` doesn't answer the most important questions:
1. What could be the user's motivation for using this library?
2. What's the difference between this library and a very similar (at a glance) and extremely popular library `MobX`? 
3. (optional) What was the author's motivation for creating this library? For example, `Redux` was created to support middleware and time-travel, `MobX` was inspired by `Proxy` API, etc.

So far, all I see are code examples, that look very similar to `MobX`

**Comment by sesm** [comment]
A good example of honest comparison to alternatives can be found in VueJS documentation: https://vuejs.org/v2/guide/comparison.html

**Comment by doasync** [comment]
@sesm, please read here about the motivation: https://gist.github.com/doasync/2017c4872f509f78f62d671006330666

**Comment by sesm** [comment]
@doasync that's a great explanation! It would be cool to add it (or at least a link to it) to README

**Comment by sesm** [comment]
I see that README is updated, I guess we can close this ticket now.
Thanks for the quick feedback!
