### ISSUE TITLE
Add `attach({ effect })` override

### ISSUE THREAD

**Issue by sergeysova** [zerobias/effector#395]
## Proposal

Ability to left `mapParams` and call `attach` just with `effect`:

```ts
const loadDataFx = attach({ effect: api.loadDataFx })
```

That means, params from attached effect passed to original effect.

## Use case

If I want just to create effect based on another effect, to differentiate `.done` and `.fail` triggers, now I must use this form:

```ts
const loadDataFx = attach({
  effect: api.loadDataFx,
  mapParams: (params) => params,
})
```

**Comment by zerobias** [comment]
Released in [effector 21.5.0](https://github.com/zerobias/effector/releases/tag/effector%4021.5.0)
