### ISSUE TITLE
Diamond problem with subscribers

### ISSUE THREAD

**Issue by artalar** [zerobias/effector#47]
```js
const clickButton = createEvent()
const closeModal = createEvent()

forward({
  from: clickButton,
  to: closeModal,
})

const lastEvent = createStore(null)
  .on(clickButton, () => 'click')
  .on(closeModal, () => 'modal')

lastEvent.watch(data => {
  // here we need everything
  sendAnalytics(data)
})

lastEvent.watch(data => {
  //here we need only final value
  render(data)
})
```

Here we are expecting two different behaviours: `sendAnalytics` need updates about both events calls, but `render` expect only last relative data.

**Comment by zerobias** [comment]
as both cases are pretty valid, we need to handle each one
as `watch` is going to become a thing on its own, we could add configuration during creation
for example

this code will be called as often as possible
```js
watch(lastEvent, {
  greedy: true,
  async handler(data) {
    sendAnalytics(data)
  },
})
```


and this one will be called only with last relevant update
```js
watch(lastEvent, {
  greedy: true,
  async handler(data) {
    render(data)
  },
})
```

what do you think?

**Comment by dundich** [comment]
maybe 
```js
greedy(lastEvent, {   //or tick(lastEvent,  or last(..., or every(.....
  async handler(data) {
    sendAnalytics(data)
  },
})
```

**Comment by zerobias** [comment]
there could be another options, e.g `skipFirst: true` for skipping first immediately appeared update

**Comment by dundich** [comment]
Can do like in Rxjs?

https://www.learnrxjs.io/operators/filtering/skip.html
```
import {  skip,filter,tap,take,takeUntil,finalize, map ....  } from 'foo-magic/operators';

const clickButton = createEvent()

const lastEvent = createStore({e:'none'}).on(clickButton, (e) => {e:'click'})

const cancel$ = createEvent();

const newEvent$  = lastEvent    // as event emitter (store, events ....   )
.pipe(  // magic combine
  takeUntil(cancel$),  // listen until no cancel event
  skip(1),  // skip ...for skipping first
  debounceTime(1000), // button-events thrash filter
  tap((state) => console.log(state)), 
  map((state) => {...state,  say: "УРА!"   }),
  tap((c) => console.log(c.say)),
  finalize(() => console.log("THE END"))
).subscribe(); // for example

// bla-bla  
for(int i=0; i<10; i++) clickButton();

lastEvent.watch((e)=> console.log('SPAM!'); )
newEvent$.watch((e)=> console.log(e.say)) // УРА!



```

**Comment by everdimension** [comment]
I don't see how `clickButton` and `closeModal` can be invoked synchronously.
I mean, they *can*, but it probably makes no sense.

If they are invoked at different points in time, then analytics will get all expected results.

So perhaps it doesn't make sense for isolated atomic actions to be invoked synchronously? And in the rare cases where it does, it might be okay to only get notified about latest state?

**Comment by artalar** [comment]
@everdimension `clickButton` trigger `closeModal` synchronously by `forward`.
My example - is just an example, not from my product code, but it is a good illustration for a diamond problem for subscribers.
Library calculation is accumulative for subscribers, what is mean under the hood all store and events dependencies (graph) calculations "flatify" and subscribers receive only last updates (even if there were several).

**Comment by zmitry** [comment]
I guess for this particular case we could add some helper which uses subscribers field
function watchGreedy(store, cb) {
store.subscribers.entries.forEach(el=>{
  el.watch(cb);
})
}

**Comment by zerobias** [comment]
implemented as `sample` for making updates non-greedy
