### ISSUE TITLE
Missed computation in `getState` for store without subscribers

### ISSUE THREAD

**Issue by artalar** [zerobias/effector#48]
Simple example: https://effector.now.sh/try?version=0.18.3-beta.1&code=MYewdgzgLgBApgNzmWBeGwBOcCGU4CiSKAFAJQBQFoks0I2AjDOlrvgMpQNwkBmOADYQ4lAJAA6cCUTIoAGhjkWAPhhRMAV1EBuKjWgx62AEwsM2PHC49+QkeKlgSxuI0XLUajdsoUA9P7wxFDkVACWfEquJhIA5nBQXFbKAISo6D6i6gAWmCAA7jBgcEUEmPmYJADkALLhECIAJhggALYADppQeOHg1WRAA

**Comment by artalar** [comment]
The code have mistake

**Comment by sergeysova** [comment]
😆
