### ISSUE TITLE
Can't set undefined value in store

### ISSUE THREAD

**Issue by mufasa71** [zerobias/effector#50]
**Code to reproduce the issue:**
https://codesandbox.io/s/lp1roln39q
**Expected behavior:**
Should reset value to undefined
**Actual behavior:**
Does not resets value in store
**Versions of packages used:**
0.18.2

**Comment by goodmind** [comment]
@mufasa71 `undefined` is special value, don't use in stores, use `null` instead

**Comment by goodmind** [comment]
I will add warning about this

**Comment by goodmind** [comment]
Fixed in 1a8fa21e1e584439415d459687ace3f4393f631c
