### ISSUE TITLE
Documentation: Valid use-cases for `Store#getState()`

### ISSUE THREAD

**Issue by supafreq** [zerobias/effector#533]
I'm creating a NodeJS web server backend API that aggregates state with Effector. It works great, but it seems that I must use `.getState` on my stores in order to actually return the data to the client when requested. Are there any problems with this? Is there a better way to use store state in request responses?

**Comment by egorguscha** [comment]
You can create events which will be executed whenever the server will get events from client(routes). Look at this [snippet](https://gist.github.com/zerobias/7eab81f592211f5971709bc406d4feb6)

**Comment by supafreq** [comment]
This seems to be a pub-sub example, which makes a lot of sense. Creating events for request-response cycles, though, seems unnecessary and I'm not sure for what benefit. Are there any specific problems with using `.getState` in a request-response cycle context?

If there is no problem, then this can serve as a documentation issue, because as of right now the documentation does not specify the situations when `.getState()` is appropriate, it only states that you don't need the method.

**Comment by supafreq** [comment]
It would seem that this is indeed a situation where this method is ideal to use in a non-testing context, and I have yet to see evidence of otherwise.

From what I understand, the danger of using `.getState()` is that you might get inconsistent in-between combinations of different Units that would not otherwise be possible through normal usage. In my use-case, I have a single store per endpoint, which is always updated atomically, so I should never run into any issues. Unless you can tell me something I'm missing.

**Comment by egorguscha** [comment]
An [Example](https://stackblitz.com/edit/node-q6batt?file=index.js), as I understood you right, you want something like this

**Comment by sergeysova** [comment]
Looks like you need [fork](https://effector.dev/docs/api/effector/fork/#fork-formulae).
You can review [Russian blog post](https://blog.kamyshev.me/effector-fork-api) section about SSR

**Comment by sergeysova** [comment]
```ts
const scope = fork();
await allSettled(myStartEvent, { scope, params: { req, res } });
// do all work
const data = serialize(scope);
res.json(data);
```
