### ISSUE TITLE
Unable to extend Fail type from standard interface Error

### ISSUE THREAD

**Issue by PvtAnimalMother** [zerobias/effector#644]
in [effector/index.d.ts](https://github.com/effector/effector/blob/master/packages/effector/index.d.ts#L141-L146)

```ts
export interface Effect<Params, Done, Fail = Error> extends Unit<Params> {
  (params: Params): Promise<Done>
  readonly done: Event<{params: Params; result: Done}>
  readonly doneData: Event<Done>
  readonly fail: Event<{params: Params; error: Fail}>
  readonly failData: Event<Fail>
```

This causes type errors when a custom error needs to be passed.

**Comment by sergeysova** [comment]
I think you don't need to extend interfaces. You need just create effect with generic parameters:

```ts
const fx = createEffect<ParamsType, DoneType, ErrorType>(ƒn);
```

You need just to pass your `ErrorType` as third generic parameter to a `createEffect`
