### ISSUE TITLE
Improve createComponent

### ISSUE THREAD

**Issue by artalar** [zerobias/effector#73]
Please, add optional initial callback to `createComponent`

Example:
```js
createComponent(
  initialProps => store.map(state => state[initialProps.id]),
  Component
)
```

**Comment by zerobias** [comment]
Isn't it the same? https://effector.now.sh/try?version=develop&code=JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFCiSyIrrZ4wAiA8gLJxEnlKbALQATErXrR4AbxgBPMFjgBlGNCwAaOLiEwsajQF8+xUmSwECWfNEnhpcGbpz6AwiUgA7LF5gn+c0trWyhhIWoaGlwIL1R4ABtgeLgAXh09A3VKAAoAbQBGbQAmbQBmbQAWAF0ASiiYuMTkmENKdHSQZDAASX0QVByaODgk+M1huGA0gD4M1yyNHOBtGS9kECwALnIx1uzlMjgAaimjWon66NiUvb6sAbS4Lt7+wcm9tqxUCZH4jVm82Q7k8sV8MCGIz+B1+UJyAH1tPFgVhaoCADxJGYyZH6IzogD0WMm9XqI2uTTglC8oiwlFE90enW6jPeIzub1hOUZ2mAaNSc3RjLgAGssPJUjJgEYCTNLg0bvAADItJ4uFEeBw+PyQqm+Wn01lcxFwXGojEAVwS2LN+IJVpmNCujRSxAg8HS4lwFs2fgAdOr9ABRBIPcE5MiiYAANzI9S9PvBfoARhBRPI-d0lDS3AALYAJUQ5N0weqsfBcbh+6kGnLolUpWXaEtXAgWrz4YCxZ4st7ogAq2hUM11-0oOy+6IAglAoMh5AOZnLJgQvDscv3+XMVE6Jwdp7P5+jh3MZJNKDALVAvKaDn6Xjk9oC9vfujlV7V6kYaEA
