### ISSUE TITLE
An effect handler is not called when you use `forward`

### ISSUE THREAD

**Issue by doasync** [zerobias/effector#75]
**Code to reproduce the issue:**
[try](https://effector.now.sh/try?version=develop&code=MYewdgzgLgBAZgUysAFgEQIZQzAvDYAJwSwQFE5FgoAKAckWRToEoA6AVwgRpoAcMATwA2IDABMWeAHwwA3gCgYMAPQqC4CCGEI2ogOb8hoiVLUwQAayUxiUDoTAwGSVJmy2EEDsKh0FAL4sCgqgkLAGAEoIAI4cXrD4RCRQ5JQI1PQGrJzcvAIiYpIy8goAkOYAQgCqAOIAXDAoGGDiOoQwAJYQMGAgsMAYwjriFk4ABnAghADuGITi4+VhWjpsc45ZIPrRcQl0ADQwBSaS5XYOTnRRsfHQnt6+-kEh5jd70OtYqDQr2robMBmdRWBTvO5QNjicAA74oX6af5sBCEQjTYFjYSCGDiTrEagEIbCEJTWbzcQ0RTKOBogC2jUYbiwGAONigIEa4ISR3MCAAbggwLAQMBgA4egAjDiwBDpAnQrxgOiwaDzKCBFgAbhJrnQzMpMAcwkadAAHua6DAgqp1ABJGAIU18DKwTqwdkwCUIGAGfQIcSvdRc6D0fTMYJAA)

**Expected behavior:**
I expect an effect handler to be called when you `forward` to the effect

**Actual behavior:**
The effect is called itself but not the handler when `foward` is used

**Versions of packages used:**
Effector v0.18.4

**Comment by zerobias** [comment]
thanks for reproducing, a fix will be published in 0.18.5 (and already available in repl)
