### ISSUE TITLE
`store.on(event ...` should replace previous reducer for that event

### ISSUE THREAD

**Issue by zerobias** [zerobias/effector#8]

**Comment by doasync** [comment]
Is it done?

**Comment by doasync** [comment]
![screenshot from 2019-03-01 20-06-36](https://user-images.githubusercontent.com/29141708/53653934-91f6b380-3c5d-11e9-9ae1-d71e1315ef67.png)

**Comment by doasync** [comment]
0.18.3 didn't do anything, that's what happened, no joy: [https://effector.now.sh/try](https://effector.now.sh/try?version=0.18.3&code=MYewdgzgLgBApgNzmWBeGwBOcCGU4CiSKAFAOQCWYWcAtslGQJQBQLoks0I2M6NeOAGUoPOCQAMrGDAB04EogYAaGCSZ8AfBnAQQAGziz9IAObkczaXIVKUq9Vp2QDRk+bIAjK2ztR1LNzY8gBmIYrEUKxBRiBhEQwaAPRJMGAgsAAWcPoADiEArvowOGAAngDuOGUsfgFAA)
Reportedly it's going to success 🙂
