### ISSUE TITLE
How i can load previously saved state snapshot?

### ISSUE THREAD

**Issue by Akiyamka** [zerobias/effector#88]
For example, I saved the current state of the repository in localStorage, and I want to restore the state after the user push button "restore last state". I do not understand from the documentation, is it possible?

**Comment by artalar** [comment]
Something like that: https://codesandbox.io/s/kkvr3j22z3
Try to clicks at "increment", then reload iframe/page and click "Read from local storage"

**Comment by Akiyamka** [comment]
Thx, that's what I need!
