### ISSUE TITLE
Throw in reducer is not cancel computation of other reducers

### ISSUE THREAD

**Issue by artalar** [zerobias/effector#90]
**Code to reproduce the issue:**
[repl](https://effector.now.sh/try?version=0.18.6&code=MYewdgzgLgBAhgEwQFRAYTgJwTAvDYTAUziiIFEA3IsKACgEoAoJ0SWUaPA40ogZSghidAAzMAkADpwdRCnRYEAGhh0A+qoDeBEFwC+DPAD5d0Zmy5Q4AD26ESZQcKJjJMsHKSoM2VRu0zWEMTGC0mGEiYAEsAMzVOWFMARlFxGCgAC0wQAHcYMCJ88kwczDoAcn4AT1oiKGjgGCJS4RhYtqIbOABbAAcAGyIK5iiYYigAV0wwIJgAKhhRKWSAZgiYQ1ZwLj7MRqJ7EB6AI2jCukTVaxt-K4zbI1xTRJgAagebZiY9g6lc0jATJ0SihSwgIZSAYgADmdAABshModfsBDtEIAAuGAAEi0lH08IY33kPiUdB0iWxqU2RgA9HSYMlklJ1kxSYpsBSgtS0qJaTAGc0bH0iMBYFkcvk6G1matxKoTpNYMRgNEiNQmWkWasYAARXBAA)

**Expected behavior:**
Throw all computation

**Actual behavior:**
Receive wrong data

**Versions of packages used:**
0.18.16

**Comment by artalar** [comment]
workaround (on russian)
<details>костыльное решение: тригер процесса (addToCard) генерирует уникальный ID, который выражает последний успешный процесс вычислений. В price (в его комбайне), мы собираем все ID со всех зависимых сторов и проверяем что они одинаковые - значит апдейт был у всех и данные релевантные - можно обновляться (возвращать новый price)</details>

**Comment by zerobias** [comment]
related issue https://github.com/zerobias/effector/issues/51

**Comment by artalar** [comment]
[Workaround](https://effector.now.sh/try?version=19.1.0&code=MYewdgzgLgBAhgEwQFRAYTgJwTAvDYTAUziiIFEA3IsKACgEoAoJ0SWUaPA40ogZSghidAAzMAkADpwdRCnRYEAGhh0A+qoDeBEFwC+DPAD5d0Zmy5Q4AD26ESZQcKJjJMsHKSoM2VRu0zWEMTGC0mGEiYAEsAMzVOWFMARlFxGCgAC0wQAHcYMCJ88kwczDoAcn4AT1oiKGjgGCJS4RhYtqIbOABbAAcAGyIK5iiYYigAV0wwIJgAKhhRKWSAZgiYQ1ZwLj7MRqJuCF7B11AegCNowroN4-6hukTVaxsGZTuTx9fVRPeNp56KAvWxGXCmRIwADUGVsTAYzCYewOUlypGAmTolFClhAQykAxAAHM6AADZCZQ7I4CHaIQABcMAAJFpKPpSQiWPIfEo6DpEozUpsjAB6EUwZLJKTrJjcxTYPlBQVpUTCmBi5o2PpEYCwLI5fJ0NqS1biIA)

**Comment by zerobias** [comment]
Throwing errors is the completely wrong way to organize business logic, you don't need it at all because of filters, created especially for such cases. It more readable and significantly less error-prone than dealing with throw on a daily basis https://share.effector.dev/0zxWY3px

**Comment by artalar** [comment]
@zerobias 
The predicate for the throw is not validation - it is just an example to testify a problem

**Comment by zerobias** [comment]
Solution testified as well. You are trying to blame for the lack of support of double binding which latest significant appearance was in AngularJS more than five years ago
